name: List All Files and Save

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List all files and subdirectories excluding .git and remove './'
        run: |
          find . -type f -not -path '*/.git/*' | sed 's|^\./||' | jq -R . | jq -s . > file_list.json

      - name: Commit and push file list
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add file_list.json
          git commit -m "Update file list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Upload file list as artifact
        uses: actions/upload-artifact@v4
        with:
          name: file_list
          path: file_list.json
