name: List All Files and Save Metadata

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies (if needed)
        run: |
          sudo apt-get install python3 python3-pip

      - name: Run Python script to gather file metadata
        run: |
          python3 filelist.py

      - name: Commit and push file list
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add file_list.json
          git commit -m "Update file list with metadata"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Upload file list with metadata as artifact
        uses: actions/upload-artifact@v4
        with:
          name: file_list_with_metadata
          path: file_list.json
