on:
  schedule:
    - cron: '*/5 0 * * *'
  push:
    branches:
      - master


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create README.md
        uses: actions-js/profile-readme@master
        with:
          username: azuremist208
          github_token: ${{ secrets.GH_TOKEN }}
          template: "TEMPLATE.md"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          
