name: Waka Readme
permissions: write-all
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  push:
  
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
